from .activities import Activity
from .evidence import Evidence
from .presenter import Presenter
from .typeActivities import TypeActivity
from .typeEvidence import TypeEvidence
from .users import User
from .universities import University
from .organizationalUnit import OrganizationalUnit
from .deadline import Deadline
